import bcrypt from 'bcryptjs';

export const initialCategories = [
  {
    _id: 'cat_starters',
    name: 'Starters & Appetizers',
    slug: 'starters',
    description: 'Crispy, smoky, flavorful bites to kickstart your meal',
    icon: 'Flame',
    displayOrder: 1,
    isActive: true,
  },
  {
    _id: 'cat_mains',
    name: 'Main Course',
    slug: 'main-course',
    description: 'Rich, aromatic gravies, curries and chef signature platters',
    icon: 'ChefHat',
    displayOrder: 2,
    isActive: true,
  },
  {
    _id: 'cat_biryani',
    name: 'Rice & Biryani',
    slug: 'rice-biryani',
    description: 'Fragrant dum cooked basmati rice with royal spices and saffron',
    icon: 'CookingPot',
    displayOrder: 3,
    isActive: true,
  },
  {
    _id: 'cat_breads',
    name: 'Tandoori Breads',
    slug: 'breads',
    description: 'Clay-oven baked naans, rotis and stuffed kulchas',
    icon: 'Wheat',
    displayOrder: 4,
    isActive: true,
  },
  {
    _id: 'cat_drinks',
    name: 'Beverages & Mocktails',
    slug: 'drinks',
    description: 'Refreshing cool sips, artisanal coolers and creamy shakes',
    icon: 'GlassWater',
    displayOrder: 5,
    isActive: true,
  },
  {
    _id: 'cat_desserts',
    name: 'Desserts & Sweets',
    slug: 'desserts',
    description: 'Indulgent sweet endings crafted with pure passion',
    icon: 'IceCream',
    displayOrder: 6,
    isActive: true,
  },
];

// Exactly 10 Curated Signature Dishes with Photorealistic Food Imagery
export const initialMenuItems = [
  // 1. Starter
  {
    _id: 'item_1',
    categoryId: 'cat_starters',
    name: 'Paneer Tikka Angara',
    description: 'Fresh cottage cheese cubes marinated in smoked tandoori spices, char-grilled with bell peppers & onions.',
    price: 320,
    originalPrice: 360,
    image: '/images/dishes/paneer_tikka.jpg',
    foodType: 'veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 2,
    preparationTime: 15,
    tags: ['Tandoor', 'Gluten Free'],
  },
  // 2. Starter
  {
    _id: 'item_2',
    categoryId: 'cat_starters',
    name: 'Murgh Malai Kebab',
    description: 'Melt-in-mouth chicken chunks steeped in cream, cardamom, mild cheese and roasted in clay oven.',
    price: 420,
    originalPrice: 460,
    image: '/images/dishes/murgh_malai.jpg',
    foodType: 'non-veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 1,
    preparationTime: 16,
    tags: ['Tandoor', 'Mild'],
  },
  // 3. Main Course
  {
    _id: 'item_3',
    categoryId: 'cat_mains',
    name: 'Old Delhi Butter Chicken',
    description: 'Tender tandoori chicken simmered in a velvety, buttery tomato gravy infused with fenugreek.',
    price: 460,
    originalPrice: 520,
    image: '/images/dishes/butter_chicken.jpg',
    foodType: 'non-veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 1,
    preparationTime: 20,
    tags: ['Signature', 'Rich'],
  },
  // 4. Main Course
  {
    _id: 'item_4',
    categoryId: 'cat_mains',
    name: 'Paneer Lababdar',
    description: 'Soft cottage cheese cubes in an aromatic cashew-tomato gravy, finished with fresh ginger juliennes.',
    price: 390,
    originalPrice: 430,
    image: '/images/dishes/paneer_lababdar.jpg',
    foodType: 'veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 2,
    preparationTime: 18,
    tags: ['Vegetarian', 'Creamy'],
  },
  // 5. Main Course
  {
    _id: 'item_5',
    categoryId: 'cat_mains',
    name: 'Dal Makhani Gold',
    description: 'Slow-cooked black lentils simmered overnight for 24 hours with churned butter and dairy cream.',
    price: 340,
    originalPrice: null,
    image: '/images/dishes/dal_makhani.jpg',
    foodType: 'veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 1,
    preparationTime: 10,
    tags: ['Classic', 'Comfort'],
  },
  // 6. Biryani
  {
    _id: 'item_6',
    categoryId: 'cat_biryani',
    name: 'Hyderabadi Dum Chicken Biryani',
    description: 'Aged basmati rice layered with spiced marinated chicken, saffron, fried onions, served with mirchi ka salan & raita.',
    price: 440,
    originalPrice: 490,
    image: '/images/dishes/chicken_biryani.jpg',
    foodType: 'non-veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 2,
    preparationTime: 18,
    tags: ['Hyderabadi', 'Dum Pukht'],
  },
  // 7. Biryani
  {
    _id: 'item_7',
    categoryId: 'cat_biryani',
    name: 'Subz Shahi Biryani',
    description: 'Garden fresh vegetables and paneer cubes infused with fragrant spices and long grain basmati rice.',
    price: 360,
    originalPrice: 390,
    image: '/images/dishes/chicken_biryani.jpg',
    foodType: 'veg',
    isAvailable: true,
    isBestseller: false,
    spicyLevel: 1,
    preparationTime: 15,
    tags: ['Veg Biryani'],
  },
  // 8. Bread
  {
    _id: 'item_8',
    categoryId: 'cat_breads',
    name: 'Garlic Butter Naan',
    description: 'Traditional refined flour leavened flatbread brushed with crushed roasted garlic and pure butter.',
    price: 95,
    originalPrice: null,
    image: '/images/dishes/garlic_naan.jpg',
    foodType: 'veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 0,
    preparationTime: 8,
    tags: ['Tandoor'],
  },
  // 9. Beverage
  {
    _id: 'item_9',
    categoryId: 'cat_drinks',
    name: 'Mango Kesar Lassi',
    description: 'Thick, creamy churned yogurt blended with Alphonso mango pulp, saffron strands and pistachios.',
    price: 180,
    originalPrice: null,
    image: '/images/dishes/mango_lassi.jpg',
    foodType: 'veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 0,
    preparationTime: 5,
    tags: ['Traditional', 'Refreshing'],
  },
  // 10. Dessert
  {
    _id: 'item_10',
    categoryId: 'cat_desserts',
    name: 'Gulab Jamun with Saffron Rabri',
    description: 'Warm golden milk dumplings soaked in cardamom sugar syrup, topped with chilled thickened saffron rabri.',
    price: 210,
    originalPrice: 240,
    image: '/images/dishes/gulab_jamun.jpg',
    foodType: 'veg',
    isAvailable: true,
    isBestseller: true,
    spicyLevel: 0,
    preparationTime: 6,
    tags: ['Dessert', 'Sweet'],
  },
];

export const initialTables = [
  { _id: 'tbl_1', tableNumber: '1', label: 'Window Booth', capacity: 4, location: 'Main Hall', status: 'available' },
  { _id: 'tbl_2', tableNumber: '2', label: 'Central Table', capacity: 2, location: 'Main Hall', status: 'available' },
  { _id: 'tbl_3', tableNumber: '3', label: 'Cozy Corner', capacity: 4, location: 'Main Hall', status: 'available' },
  { _id: 'tbl_4', tableNumber: '4', label: 'Family Banquet', capacity: 6, location: 'Main Hall', status: 'available' },
  { _id: 'tbl_5', tableNumber: '5', label: 'Rooftop Cabana', capacity: 4, location: 'Terrace', status: 'available' },
  { _id: 'tbl_6', tableNumber: '6', label: 'Garden View', capacity: 4, location: 'Outdoor Garden', status: 'available' },
  { _id: 'tbl_7', tableNumber: '7', label: 'Lounge High-top', capacity: 2, location: 'Bar Lounge', status: 'available' },
  { _id: 'tbl_8', tableNumber: '8', label: 'VIP Dining Suite', capacity: 8, location: 'Private Dining', status: 'available' },
];

export const initialSettings = {
  restaurantName: 'Saffron & Spice Bistro',
  tagline: 'Authentic Flavors, Modern Dine-In Experience',
  logo: '',
  phone: '+91 98765 43210',
  email: 'dine@saffronspice.com',
  address: '42 Culinary Avenue, Gourmet District, Bangalore 560001',
  timings: 'Mon - Sun: 11:30 AM to 11:00 PM',
  currency: 'INR',
  currencySymbol: '₹',
  taxPercentage: 5,
  isOnlinePaymentEnabled: true,
  isPayAtCounterEnabled: true,
  announcementBanner: '✨ Chef Specials available today! Enjoy free garlic naan with every main course order.',
};

export const defaultAdmin = {
  _id: 'user_admin_1',
  name: 'Restaurant Manager',
  email: 'admin@restaurant.com',
  passwordHash: '$2a$10$w8T0h4c/1kQZ2b1h3n4s5eO2v3Xy9z9q8w7e6r5t4y3u2i1o0p.', // 'admin123'
  role: 'admin',
};
